#############################################################################
# Generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#  Apr 07, 2026 02:04:23 PM CEST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


#######  Default Fonts ########
set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkTooltipFont
set vTcl(actual_gui_font_tooltip_name)  TkTooltipFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) Relative
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base

############ toplevel.wgt #############################
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -borderwidth 0 -menu $top.m84 -relief flat -background #d9d9d9 -container 0 \
        -height 0 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -padx 0 -pady 0 -takefocus 0 -width 0 
    wm focusmodel $top passive
    wm geometry $top 1896x976+5+11
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1066
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Inventaris"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel0" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
# add aa target = .top1.m84, basename = $top.m84
    menu "$top.m84" \
        -activebackground #d9d9d9 -activeborderwidth 1 \
        -activeforeground black -background #d9d9d9 -borderwidth 1 \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground #000000 \
        -relief flat -selectcolor SystemMenuText -takefocus 0 -tearoff 0 \
        -type normal 
# add first menu widget
    labelframe "$top.lab55" \
        -borderwidth 2 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -labelanchor nw -relief groove -text "Output" \
        -background #d9d9d9 -container 0 -height 698 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -padx 0 -pady 0 -takefocus 0 -width 1882 
    vTcl:DefineAlias "$top.lab55" "outputLabelframe" vTcl:WidgetProc "Toplevel0" 1
    set site_3_0 $top.lab55
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd "$site_3_0.scr56" \
        -borderwidth 0 -relief flat -background #d9d9d9 -container 0 \
        -height 15 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -padx 0 -pady 0 -takefocus 0 -width 30 
    vTcl:DefineAlias "$site_3_0.scr56" "Scrolledtreeview1" vTcl:WidgetProc "Toplevel0" 1
    bind $site_3_0.scr56 <Button-1> {
        lambda e: OnTreeviewClick(e)
    }

        $base.lab55.scr56.01 configure -columns "Col1 Col2 Col3 Col4 Col5 Col6 Col7 Col8" -height 4
        $base.lab55.scr56.01 configure -columns {Col1 Col2 Col3 Col4 Col5 Col6 Col7 Col8}
        $base.lab55.scr56.01 heading #0 -text {NVT}
        $base.lab55.scr56.01 heading #0 -anchor center
        $base.lab55.scr56.01 column #0 -width 68
        $base.lab55.scr56.01 column #0 -minwidth 0
        $base.lab55.scr56.01 column #0 -stretch 1
        $base.lab55.scr56.01 column #0 -anchor w
        $base.lab55.scr56.01 heading Col1 -text {Categorie}
        $base.lab55.scr56.01 heading Col1 -anchor center
        $base.lab55.scr56.01 column Col1 -width 262
        $base.lab55.scr56.01 column Col1 -minwidth 100
        $base.lab55.scr56.01 column Col1 -stretch 1
        $base.lab55.scr56.01 column Col1 -anchor center
        $base.lab55.scr56.01 heading Col2 -text {Productnummer}
        $base.lab55.scr56.01 heading Col2 -anchor center
        $base.lab55.scr56.01 column Col2 -width 303
        $base.lab55.scr56.01 column Col2 -minwidth 100
        $base.lab55.scr56.01 column Col2 -stretch 1
        $base.lab55.scr56.01 column Col2 -anchor center
        $base.lab55.scr56.01 heading Col3 -text {Totaal}
        $base.lab55.scr56.01 heading Col3 -anchor center
        $base.lab55.scr56.01 column Col3 -width 149
        $base.lab55.scr56.01 column Col3 -minwidth 100
        $base.lab55.scr56.01 column Col3 -stretch 1
        $base.lab55.scr56.01 column Col3 -anchor center
        $base.lab55.scr56.01 heading Col4 -text {A Kwaliteit}
        $base.lab55.scr56.01 heading Col4 -anchor center
        $base.lab55.scr56.01 column Col4 -width 132
        $base.lab55.scr56.01 column Col4 -minwidth 100
        $base.lab55.scr56.01 column Col4 -stretch 1
        $base.lab55.scr56.01 column Col4 -anchor center
        $base.lab55.scr56.01 heading Col5 -text {B Kwaliteit}
        $base.lab55.scr56.01 heading Col5 -anchor center
        $base.lab55.scr56.01 column Col5 -width 101
        $base.lab55.scr56.01 column Col5 -minwidth 100
        $base.lab55.scr56.01 column Col5 -stretch 1
        $base.lab55.scr56.01 column Col5 -anchor center
        $base.lab55.scr56.01 heading Col6 -text {C Kwaliteit}
        $base.lab55.scr56.01 heading Col6 -anchor center
        $base.lab55.scr56.01 column Col6 -width 102
        $base.lab55.scr56.01 column Col6 -minwidth 100
        $base.lab55.scr56.01 column Col6 -stretch 1
        $base.lab55.scr56.01 column Col6 -anchor center
        $base.lab55.scr56.01 heading Col7 -text {Locatie}
        $base.lab55.scr56.01 heading Col7 -anchor center
        $base.lab55.scr56.01 column Col7 -width 247
        $base.lab55.scr56.01 column Col7 -minwidth 100
        $base.lab55.scr56.01 column Col7 -stretch 1
        $base.lab55.scr56.01 column Col7 -anchor center
        $base.lab55.scr56.01 heading Col8 -text {Opmerking}
        $base.lab55.scr56.01 heading Col8 -anchor center
        $base.lab55.scr56.01 column Col8 -width 453
        $base.lab55.scr56.01 column Col8 -minwidth 400
        $base.lab55.scr56.01 column Col8 -stretch 1
        $base.lab55.scr56.01 column Col8 -anchor center
    vTcl:copy_lock $site_3_0.scr56
# add p1 basename = $site_3_0.scr56
    place $site_3_0.scr56 \
        -in $site_3_0 -x 0 -relx 0.005 -y 0 -rely 0.029 -width 0 \
        -relwidth 0.988 -height 0 -relheight 0.957 -anchor nw \
        -bordermode ignore 
    labelframe "$top.lab54" \
        -borderwidth 2 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -labelanchor nw -relief groove -text "Zoeken" \
        -background #d9d9d9 -container 0 -height 286 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -padx 0 -pady 0 -takefocus 0 -width 1882 
    vTcl:DefineAlias "$top.lab54" "inputLabelframe" vTcl:WidgetProc "Toplevel0" 1
    set site_3_0 $top.lab54
    labelframe "$site_3_0.lab59" \
        -borderwidth 2 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -labelanchor nw -relief groove \
        -text "Kies categorie" -background #d9d9d9 -container 0 -height 143 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -padx 0 -pady 0 -takefocus 0 -width 478 
    vTcl:DefineAlias "$site_3_0.lab59" "nieuwLabelframe" vTcl:WidgetProc "Toplevel0" 1
    set site_4_0 $site_3_0.lab59
    radiobutton "$site_4_0.rad50" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 25 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 1 -indicatoron 1 \
        -justify left -offrelief raised -padx 1 -pady 1 -relief flat \
        -selectcolor SystemWindow -state normal -text "Desktops" \
        -underline -1 -value "desktops" -variable "radioVar" -width 105 \
        -wraplength 0 
    vTcl:DefineAlias "$site_4_0.rad50" "RbtnDesktops" vTcl:WidgetProc "Toplevel0" 1
    radiobutton "$site_4_0.rad57" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 25 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 1 -indicatoron 1 \
        -justify left -offrelief raised -padx 1 -pady 1 -relief flat \
        -selectcolor SystemWindow -state normal -text "Voedingen" \
        -underline -1 -value "voedingen" -variable "radioVar" -width 107 \
        -wraplength 0 
    vTcl:DefineAlias "$site_4_0.rad57" "RbtnVoedingen" vTcl:WidgetProc "Toplevel0" 1
    radiobutton "$site_4_0.rad58" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 25 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 1 -indicatoron 1 \
        -justify left -offrelief raised -padx 1 -pady 1 -relief flat \
        -selectcolor SystemWindow -state normal -text "Mobiels" -underline -1 \
        -value "mobiels" -variable "radioVar" -width 87 -wraplength 0 
    vTcl:DefineAlias "$site_4_0.rad58" "RbtnMobiels" vTcl:WidgetProc "Toplevel0" 1
    radiobutton "$site_4_0.rad52" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 25 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 1 -indicatoron 1 \
        -justify left -offrelief raised -padx 1 -pady 1 -relief flat \
        -selectcolor SystemWindow -state normal -text "Laptops" -underline -1 \
        -value "laptops" -variable "radioVar" -width 97 -wraplength 0 
    vTcl:DefineAlias "$site_4_0.rad52" "RbtnLaptops" vTcl:WidgetProc "Toplevel0" 1
    radiobutton "$site_4_0.rad56" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 25 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 1 -indicatoron 1 \
        -justify left -offrelief raised -padx 1 -pady 1 -relief flat \
        -selectcolor SystemWindow -state normal -text "Kabels" -underline -1 \
        -value "kabels" -variable "radioVar" -width 84 -wraplength 0 
    vTcl:DefineAlias "$site_4_0.rad56" "RbtnKabels" vTcl:WidgetProc "Toplevel0" 1
    radiobutton "$site_4_0.rad55" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 25 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 1 -indicatoron 1 \
        -justify left -offrelief raised -padx 1 -pady 1 -relief flat \
        -selectcolor SystemWindow -state normal -text "Muizen" -underline -1 \
        -value "muizen" -variable "radioVar" -width 88 -wraplength 0 
    vTcl:DefineAlias "$site_4_0.rad55" "RbtnMuizen" vTcl:WidgetProc "Toplevel0" 1
    radiobutton "$site_4_0.rad54" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 25 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 1 -indicatoron 1 \
        -justify left -offrelief raised -padx 1 -pady 1 -relief flat \
        -selectcolor SystemWindow -state normal -text "Toetsenborden" \
        -underline -1 -value "toetsenborden" -variable "radioVar" -width 144 \
        -wraplength 0 
    vTcl:DefineAlias "$site_4_0.rad54" "RbtnToestenborden" vTcl:WidgetProc "Toplevel0" 1
    radiobutton "$site_4_0.rad53" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 26 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 1 -indicatoron 1 \
        -justify left -offrelief raised -padx 1 -pady 1 -relief flat \
        -selectcolor SystemWindow -state normal -text "Beeldschermen" \
        -underline -1 -value "beeldschermen" -variable "radioVar" -width 147 \
        -wraplength 0 
    vTcl:DefineAlias "$site_4_0.rad53" "RbtnBeeldschermen" vTcl:WidgetProc "Toplevel0" 1
    label "$site_4_0.lab59" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 \
        -text "Voeg nieuw item toe in gekozen categorie:" -underline -1 \
        -width 335 -wraplength 0 
    vTcl:DefineAlias "$site_4_0.lab59" "voegtoeLabel" vTcl:WidgetProc "Toplevel0" 1
    button "$site_4_0.but51" \
        -activebackground #d9d9d9 -activeforeground black -anchor center \
        -background #d9d9d9 -borderwidth 2 -command "on_btnGaan" \
        -compound left -default disabled -disabledforeground #a3a3a3 \
        -font "-family {DejaVu Sans} -size 12" -foreground #000000 -height 30 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 1 -justify center -padx 1 -pady 1 -relief raised \
        -repeatdelay 0 -repeatinterval 0 -state normal -text "Gaan" \
        -underline -1 -width 90 -wraplength 0 
    vTcl:DefineAlias "$site_4_0.but51" "btnGaan" vTcl:WidgetProc "Toplevel0" 1
# add p1 basename = $site_4_0.rad50
    place $site_4_0.rad50 \
        -in $site_4_0 -x 0 -relx 0.017 -y 0 -rely 0.21 -width 0 \
        -relwidth 0.22 -height 0 -relheight 0.175 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.rad57
    place $site_4_0.rad57 \
        -in $site_4_0 -x 0 -relx 0.753 -y 0 -rely 0.21 -width 0 \
        -relwidth 0.224 -height 0 -relheight 0.175 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.rad58
    place $site_4_0.rad58 \
        -in $site_4_0 -x 0 -relx 0.753 -y 0 -rely 0.49 -width 0 \
        -relwidth 0.182 -height 0 -relheight 0.175 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.rad52
    place $site_4_0.rad52 \
        -in $site_4_0 -x 0 -relx 0.017 -y 0 -rely 0.49 -width 0 \
        -relwidth 0.203 -height 0 -relheight 0.175 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.rad56
    place $site_4_0.rad56 \
        -in $site_4_0 -x 0 -relx 0.565 -y 0 -rely 0.49 -width 0 \
        -relwidth 0.176 -height 0 -relheight 0.172 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.rad55
    place $site_4_0.rad55 \
        -in $site_4_0 -x 0 -relx 0.565 -y 0 -rely 0.207 -width 0 \
        -relwidth 0.184 -height 0 -relheight 0.172 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.rad54
    place $site_4_0.rad54 \
        -in $site_4_0 -x 0 -relx 0.251 -y 0 -rely 0.49 -width 0 \
        -relwidth 0.301 -height 0 -relheight 0.172 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.rad53
    place $site_4_0.rad53 \
        -in $site_4_0 -x 0 -relx 0.251 -y 0 -rely 0.207 -width 0 \
        -relwidth 0.308 -height 0 -relheight 0.179 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.lab59
    place $site_4_0.lab59 \
        -in $site_4_0 -x 0 -relx 0.023 -y 0 -rely 0.772 -width 0 \
        -relwidth 0.701 -height 0 -relheight 0.145 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.but51
    place $site_4_0.but51 \
        -in $site_4_0 -x 0 -relx 0.753 -y 0 -rely 0.759 -width 90 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    labelframe "$site_3_0.lab50" \
        -borderwidth 2 -font "TkDefaultFont" -foreground #000000 \
        -labelanchor nw -relief groove -background #d9d9d9 -container 0 \
        -height 95 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -padx 0 -pady 0 -takefocus 0 -width 899 
    vTcl:DefineAlias "$site_3_0.lab50" "verwijderLabelframe" vTcl:WidgetProc "Toplevel0" 1
    set site_4_0 $site_3_0.lab50
    label "$site_4_0.lab52" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 \
        -text "Geselecteerde item verwijderen:" -underline -1 -width 256 \
        -wraplength 0 
    vTcl:DefineAlias "$site_4_0.lab52" "verwijderLabel" vTcl:WidgetProc "Toplevel0" 1
    button "$site_4_0.but68" \
        -activebackground #d9d9d9 -activeforeground black -anchor center \
        -background #d9d9d9 -borderwidth 2 -command "on_btnTerug" \
        -compound left -default disabled -disabledforeground #a3a3a3 \
        -font "-family {DejaVu Sans} -size 12" -foreground #000000 -height 26 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 1 -justify center -padx 1 -pady 1 -relief raised \
        -repeatdelay 0 -repeatinterval 0 -state normal -text "Terug" \
        -underline -1 -width 77 -wraplength 0 
    vTcl:DefineAlias "$site_4_0.but68" "btnTerug" vTcl:WidgetProc "Toplevel0" 1
    button "$site_4_0.but51" \
        -activebackground #d9d9d9 -activeforeground black -anchor center \
        -background #d9d9d9 -borderwidth 2 -command "on_btnVerwijder" \
        -compound left -default disabled -disabledforeground #a3a3a3 \
        -font "-family {DejaVu Sans} -size 12" -foreground #000000 -height 36 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 1 -justify center -padx 1 -pady 1 -relief raised \
        -repeatdelay 0 -repeatinterval 0 -state normal -text "Verwijder" \
        -underline -1 -width 77 -wraplength 0 
    vTcl:DefineAlias "$site_4_0.but51" "btnVerwijder" vTcl:WidgetProc "Toplevel0" 1
    button "$site_4_0.but56" \
        -activebackground #d9d9d9 -activeforeground black -anchor center \
        -background #d9d9d9 -borderwidth 2 -command "on_btnLog" \
        -compound left -default disabled -disabledforeground #a3a3a3 \
        -font "-family {DejaVu Sans} -size 12" -foreground #000000 -height 26 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 1 -justify center -padx 1 -pady 1 -relief raised \
        -repeatdelay 0 -repeatinterval 0 -state normal -text "Kiezen" \
        -underline -1 -width 77 -wraplength 0 
    vTcl:DefineAlias "$site_4_0.but56" "btnLog" vTcl:WidgetProc "Toplevel0" 1
    label "$site_4_0.lab66" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 \
        -text "Terug naar voorraad database:" -underline -1 -width 247 \
        -wraplength 0 
    vTcl:DefineAlias "$site_4_0.lab66" "terugLabel" vTcl:WidgetProc "Toplevel0" 1
    label "$site_4_0.lab57" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 \
        -text "Logboek database inzien:" -underline -1 -width 207 \
        -wraplength 0 
    vTcl:DefineAlias "$site_4_0.lab57" "logLabel" vTcl:WidgetProc "Toplevel0" 1
# add p1 basename = $site_4_0.lab52
    place $site_4_0.lab52 \
        -in $site_4_0 -x 0 -relx 0.031 -y 0 -rely 0.211 -width 0 \
        -relwidth 0.285 -height 0 -relheight 0.253 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.but68
    place $site_4_0.but68 \
        -in $site_4_0 -x 0 -relx 0.79 -y 0 -rely 0.526 -width 100 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_4_0.but51
    place $site_4_0.but51 \
        -in $site_4_0 -x 0 -relx 0.1 -y 0 -rely 0.526 -width 100 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_4_0.but56
    place $site_4_0.but56 \
        -in $site_4_0 -x 0 -relx 0.423 -y 0 -rely 0.526 -width 100 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_4_0.lab66
    place $site_4_0.lab66 \
        -in $site_4_0 -x 0 -relx 0.69 -y 0 -rely 0.211 -width 0 \
        -relwidth 0.275 -height 0 -relheight 0.253 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.lab57
    place $site_4_0.lab57 \
        -in $site_4_0 -x 0 -relx 0.378 -y 0 -rely 0.211 -width 0 \
        -relwidth 0.23 -height 0 -relheight 0.253 -anchor nw \
        -bordermode ignore 
    button "$site_3_0.but54" \
        -activebackground #d9d9d9 -activeforeground black -anchor center \
        -background #d9d9d9 -borderwidth 2 -command "on_btnAfsluiten" \
        -compound left -default disabled -disabledforeground #a3a3a3 \
        -font "-family {DejaVu Sans} -size 12" -foreground #000000 -height 36 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 1 -justify center -padx 1 -pady 1 -relief raised \
        -repeatdelay 0 -repeatinterval 0 -state normal -text "Afsluiten" \
        -underline -1 -width 77 -wraplength 0 
    vTcl:DefineAlias "$site_3_0.but54" "btnAfsluiten" vTcl:WidgetProc "Toplevel0" 1
    button "$site_3_0.but59" \
        -activebackground #d9d9d9 -activeforeground black -anchor center \
        -background #d9d9d9 -borderwidth 2 -command "on_btnZoeken" \
        -compound left -default disabled -disabledforeground #a3a3a3 \
        -font "-family {DejaVu Sans} -size 12" -foreground #000000 -height 36 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 1 -justify center -padx 1 -pady 1 -relief raised \
        -repeatdelay 0 -repeatinterval 0 -state normal -text "Zoeken" \
        -underline -1 -width 77 -wraplength 0 
    vTcl:DefineAlias "$site_3_0.but59" "btnZoeken" vTcl:WidgetProc "Toplevel0" 1
    label "$site_3_0.lab51" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 \
        -text "Zoek in Categorie:" -underline -1 -width 153 -wraplength 0 
    vTcl:DefineAlias "$site_3_0.lab51" "categorieLabel" vTcl:WidgetProc "Toplevel0" 1
    label "$site_3_0.lab58" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 -text "Zoek op merk:" \
        -underline -1 -width 138 -wraplength 0 
    vTcl:DefineAlias "$site_3_0.lab58" "zoekLabelMerk" vTcl:WidgetProc "Toplevel0" 1
    label "$site_3_0.lab52" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 \
        -text "Zoek op model:" -underline -1 -width 138 -wraplength 0 
    vTcl:DefineAlias "$site_3_0.lab52" "zoekLabelModel" vTcl:WidgetProc "Toplevel0" 1
    entry "$site_3_0.ent49" \
        -background #ffffff -borderwidth 1 -cursor xterm \
        -disabledbackground SystemButtonFace -disabledforeground #a3a3a3 \
        -exportselection 0 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 \
        -insertbackground #000000 -insertborderwidth 0 -insertofftime 300 \
        -insertontime 600 -insertwidth 2 -justify left \
        -readonlybackground SystemButtonFace -relief sunken \
        -selectbackground #d9d9d9 -selectborderwidth 0 \
        -selectforeground black -state normal -validate none -width 170 
    vTcl:DefineAlias "$site_3_0.ent49" "zoekEntryModel" vTcl:WidgetProc "Toplevel0" 1
    bind $site_3_0.ent49 <Key-Return> {
        lambda e: zoekbalk_enterkey(e)
    }
    entry "$site_3_0.ent57" \
        -background #ffffff -borderwidth 1 -cursor xterm \
        -disabledbackground SystemButtonFace -disabledforeground #a3a3a3 \
        -exportselection 0 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 \
        -insertbackground #000000 -insertborderwidth 0 -insertofftime 300 \
        -insertontime 600 -insertwidth 2 -justify left \
        -readonlybackground SystemButtonFace -relief sunken \
        -selectbackground #d9d9d9 -selectborderwidth 0 \
        -selectforeground black -state normal -validate none -width 160 
    vTcl:DefineAlias "$site_3_0.ent57" "zoekEntryMerk" vTcl:WidgetProc "Toplevel0" 1
    bind $site_3_0.ent57 <Key-Return> {
        lambda e: zoekbalk_enterkey(e)
    }
    menubutton "$site_3_0.men61" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 1 -direction below \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 35 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -indicatoron 1 \
        -justify center -menu $top.lab54.men61.m -padx 5 -pady 4 -relief raised -compound left \
        -state normal -takefocus 0 -text "Desktops" -underline -1 -width 145 \
        -wraplength 0 
    vTcl:DefineAlias "$site_3_0.men61" "Menubtn_zoek" vTcl:WidgetProc "Toplevel0" 1
# add aa target = .top1.lab54.men61.m, basename = $site_3_0.men61.m
    menu "$site_3_0.men61.m" \
        -activebackground SystemHighlight -activeborderwidth 1 \
        -activeforeground SystemHighlightText -background #d9d9d9 \
        -borderwidth 1 -cursor arrow -disabledforeground #a3a3a3 \
        -font "TkMenuFont" -foreground #000000 -relief flat \
        -selectcolor SystemMenuText -takefocus 0 -tearoff 0 -type normal 
# add first menu widget
    $site_3_0.men61.m add command \
        -command "#on_menuDesktop" -compound left \
        -font "-family {Arial} -size 12" -label "Desktops" 
# add 5a
    $site_3_0.men61.m add command \
        -command "#on_menuLaptop" -compound left \
        -font "-family {Arial} -size 12" -label "Laptops" 
# add 5a
    $site_3_0.men61.m add command \
        -command "#on_menuToetsenbord" -compound left \
        -font "-family {Arial} -size 12" -label "Toetsenborden" 
# add 5a
    $site_3_0.men61.m add command \
        -command "#on_menuBeeldscherm" -compound left \
        -font "-family {Arial} -size 12" -label "Beeldschermen" 
# add 5a
    $site_3_0.men61.m add command \
        -command "#on_menuKabel" -compound left \
        -font "-family {Arial} -size 12" -label "Kabels" 
# add 5a
    $site_3_0.men61.m add command \
        -command "#on_menuMobiel" -compound left \
        -font "-family {Arial} -size 12" -label "Mobiels" 
# add 5a
    $site_3_0.men61.m add command \
        -command "#on_menuVoeding" -compound left \
        -font "-family {Arial} -size 12" -label "Voedingen" 
# add 5a
    $site_3_0.men61.m add command \
        -command "#on_menuMuis" -compound left \
        -font "-family {Arial} -size 12" -label "Muizen" 
# add 5a
    labelframe "$site_3_0.lab49" \
        -borderwidth 2 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -labelanchor nw -relief groove \
        -text "Item aanpassen of toevoegen" -background #d9d9d9 -container 0 \
        -height 145 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -padx 0 -pady 0 -takefocus 0 -width 1360 
    vTcl:DefineAlias "$site_3_0.lab49" "aanpassenLabelframe" vTcl:WidgetProc "Toplevel0" 1
    set site_4_0 $site_3_0.lab49
    label "$site_4_0.lab87" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 -text "Opmerking:" \
        -underline -1 -width 100 -wraplength 0 
    vTcl:DefineAlias "$site_4_0.lab87" "ItemLabelOpmerking" vTcl:WidgetProc "Toplevel0" 1
    spinbox "$site_4_0.spi72" \
        -activebackground #d9d9d9 -background white -borderwidth 1 \
        -buttonbackground SystemButtonFace -buttondownrelief raised \
        -buttonuprelief raised -cursor xterm \
        -disabledbackground SystemButtonFace -disabledforeground #a3a3a3 \
        -exportselection 0 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -from 0.0 -highlightbackground black \
        -highlightcolor #000000 -highlightthickness 0 -increment 1.0 \
        -insertbackground #000000 -insertborderwidth 0 -insertofftime 300 \
        -insertontime 600 -insertwidth 2 -justify left -relief sunken \
        -readonlybackground SystemButtonFace -repeatdelay 400 \
        -repeatinterval 100 -selectbackground #d9d9d9 -selectborderwidth 0 \
        -selectforeground black -state normal -to 100.0 -validate none \
        -width 52 -wrap 0 
    vTcl:DefineAlias "$site_4_0.spi72" "Spinbox4" vTcl:WidgetProc "Toplevel0" 1
    entry "$site_4_0.ent77" \
        -background #ffffff -borderwidth 1 -cursor xterm \
        -disabledbackground SystemButtonFace -disabledforeground #a3a3a3 \
        -exportselection 0 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -highlightbackground #c0c0c0 \
        -highlightcolor #000000 -highlightthickness 0 \
        -insertbackground #000000 -insertborderwidth 0 -insertofftime 300 \
        -insertontime 600 -insertwidth 2 -justify left \
        -readonlybackground SystemButtonFace -relief sunken \
        -selectbackground #d9d9d9 -selectborderwidth 0 \
        -selectforeground black -state normal -validate none -width 104 
    vTcl:DefineAlias "$site_4_0.ent77" "Entry1" vTcl:WidgetProc "Toplevel0" 1
    entry "$site_4_0.ent79" \
        -background #ffffff -borderwidth 1 -cursor xterm \
        -disabledbackground SystemButtonFace -disabledforeground #a3a3a3 \
        -exportselection 0 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -highlightbackground #c0c0c0 \
        -highlightcolor #000000 -highlightthickness 0 \
        -insertbackground #000000 -insertborderwidth 0 -insertofftime 300 \
        -insertontime 600 -insertwidth 2 -justify left \
        -readonlybackground SystemButtonFace -relief sunken \
        -selectbackground #d9d9d9 -selectborderwidth 0 \
        -selectforeground black -state normal -validate none -width 104 
    vTcl:DefineAlias "$site_4_0.ent79" "Entry2" vTcl:WidgetProc "Toplevel0" 1
    entry "$site_4_0.ent85" \
        -background #ffffff -borderwidth 1 -cursor xterm \
        -disabledbackground SystemButtonFace -disabledforeground #a3a3a3 \
        -exportselection 0 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -highlightbackground #c0c0c0 \
        -highlightcolor #000000 -highlightthickness 0 \
        -insertbackground #000000 -insertborderwidth 0 -insertofftime 300 \
        -insertontime 600 -insertwidth 2 -justify left \
        -readonlybackground SystemButtonFace -relief sunken \
        -selectbackground #d9d9d9 -selectborderwidth 0 \
        -selectforeground black -state normal -validate none -width 104 
    vTcl:DefineAlias "$site_4_0.ent85" "Entry3" vTcl:WidgetProc "Toplevel0" 1
    entry "$site_4_0.ent81" \
        -background #ffffff -borderwidth 1 -cursor xterm \
        -disabledbackground SystemButtonFace -disabledforeground #a3a3a3 \
        -exportselection 0 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -highlightbackground #c0c0c0 \
        -highlightcolor #000000 -highlightthickness 0 \
        -insertbackground #000000 -insertborderwidth 0 -insertofftime 300 \
        -insertontime 600 -insertwidth 2 -justify left \
        -readonlybackground SystemButtonFace -relief sunken \
        -selectbackground #d9d9d9 -selectborderwidth 0 \
        -selectforeground black -state normal -validate none -width 104 
    vTcl:DefineAlias "$site_4_0.ent81" "Entry4" vTcl:WidgetProc "Toplevel0" 1
    entry "$site_4_0.ent84" \
        -background #ffffff -borderwidth 1 -cursor xterm \
        -disabledbackground SystemButtonFace -disabledforeground #a3a3a3 \
        -exportselection 0 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -highlightbackground #c0c0c0 \
        -highlightcolor #000000 -highlightthickness 0 \
        -insertbackground #000000 -insertborderwidth 0 -insertofftime 300 \
        -insertontime 600 -insertwidth 2 -justify left \
        -readonlybackground SystemButtonFace -relief sunken \
        -selectbackground #d9d9d9 -selectborderwidth 0 \
        -selectforeground black -state normal -validate none -width 104 
    vTcl:DefineAlias "$site_4_0.ent84" "Entry5" vTcl:WidgetProc "Toplevel0" 1
    entry "$site_4_0.ent80" \
        -background #ffffff -borderwidth 1 -cursor xterm \
        -disabledbackground SystemButtonFace -disabledforeground #a3a3a3 \
        -exportselection 0 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -highlightbackground #c0c0c0 \
        -highlightcolor #000000 -highlightthickness 0 \
        -insertbackground #000000 -insertborderwidth 0 -insertofftime 300 \
        -insertontime 600 -insertwidth 2 -justify left \
        -readonlybackground SystemButtonFace -relief sunken \
        -selectbackground #d9d9d9 -selectborderwidth 0 \
        -selectforeground black -state normal -validate none -width 104 
    vTcl:DefineAlias "$site_4_0.ent80" "Entry6" vTcl:WidgetProc "Toplevel0" 1
    label "$site_4_0.lab63" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 -text "Labelint1" \
        -underline -1 -width 83 -wraplength 0 
    vTcl:DefineAlias "$site_4_0.lab63" "ItemLabelint1" vTcl:WidgetProc "Toplevel0" 1
    label "$site_4_0.lab65" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 -text "Labelint2" \
        -underline -1 -width 83 -wraplength 0 
    vTcl:DefineAlias "$site_4_0.lab65" "ItemLabelint2" vTcl:WidgetProc "Toplevel0" 1
    label "$site_4_0.lab64" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 -text "Labelint3" \
        -underline -1 -width 83 -wraplength 0 
    vTcl:DefineAlias "$site_4_0.lab64" "ItemLabelint3" vTcl:WidgetProc "Toplevel0" 1
    label "$site_4_0.lab70" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 -text "Labelint4" \
        -underline -1 -width 83 -wraplength 0 
    vTcl:DefineAlias "$site_4_0.lab70" "ItemLabelint4" vTcl:WidgetProc "Toplevel0" 1
    label "$site_4_0.lab73" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 -text "Text1" \
        -underline -1 -width 70 -wraplength 0 
    vTcl:DefineAlias "$site_4_0.lab73" "ItemLabeltext1" vTcl:WidgetProc "Toplevel0" 1
    label "$site_4_0.lab74" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 -text "Text2" \
        -underline -1 -width 68 -wraplength 0 
    vTcl:DefineAlias "$site_4_0.lab74" "ItemLabeltext2" vTcl:WidgetProc "Toplevel0" 1
    label "$site_4_0.lab83" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 -text "Text3" \
        -underline -1 -width 68 -wraplength 0 
    vTcl:DefineAlias "$site_4_0.lab83" "ItemLabeltext3" vTcl:WidgetProc "Toplevel0" 1
    label "$site_4_0.lab76" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 -text "Text4" \
        -underline -1 -width 68 -wraplength 0 
    vTcl:DefineAlias "$site_4_0.lab76" "ItemLabeltext4" vTcl:WidgetProc "Toplevel0" 1
    label "$site_4_0.lab82" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 -text "Text5" \
        -underline -1 -width 68 -wraplength 0 
    vTcl:DefineAlias "$site_4_0.lab82" "ItemLabeltext5" vTcl:WidgetProc "Toplevel0" 1
    label "$site_4_0.lab75" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 -text "Text6" \
        -underline -1 -width 68 -wraplength 0 
    vTcl:DefineAlias "$site_4_0.lab75" "ItemLabeltext6" vTcl:WidgetProc "Toplevel0" 1
    spinbox "$site_4_0.spi68" \
        -activebackground #d9d9d9 -background white -borderwidth 1 \
        -buttonbackground SystemButtonFace -buttondownrelief raised \
        -buttonuprelief raised -cursor xterm \
        -disabledbackground SystemButtonFace -disabledforeground #a3a3a3 \
        -exportselection 0 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -from 0.0 -highlightbackground black \
        -highlightcolor #000000 -highlightthickness 0 -increment 1.0 \
        -insertbackground #000000 -insertborderwidth 0 -insertofftime 300 \
        -insertontime 600 -insertwidth 2 -justify left -relief sunken \
        -readonlybackground SystemButtonFace -repeatdelay 400 \
        -repeatinterval 100 -selectbackground #d9d9d9 -selectborderwidth 0 \
        -selectforeground black -state normal -to 100.0 -validate none \
        -width 52 -wrap 0 
    vTcl:DefineAlias "$site_4_0.spi68" "Spinbox2" vTcl:WidgetProc "Toplevel0" 1
    spinbox "$site_4_0.spi67" \
        -activebackground #d9d9d9 -background white -borderwidth 1 \
        -buttonbackground SystemButtonFace -buttondownrelief raised \
        -buttonuprelief raised -cursor xterm \
        -disabledbackground SystemButtonFace -disabledforeground #a3a3a3 \
        -exportselection 0 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -from 0.0 -highlightbackground black \
        -highlightcolor #000000 -highlightthickness 0 -increment 1.0 \
        -insertbackground #000000 -insertborderwidth 0 -insertofftime 300 \
        -insertontime 600 -insertwidth 2 -justify left -relief sunken \
        -readonlybackground SystemButtonFace -repeatdelay 400 \
        -repeatinterval 100 -selectbackground #d9d9d9 -selectborderwidth 0 \
        -selectforeground black -state normal -to 100.0 -validate none \
        -width 52 -wrap 0 
    vTcl:DefineAlias "$site_4_0.spi67" "Spinbox3" vTcl:WidgetProc "Toplevel0" 1
    spinbox "$site_4_0.spi60" \
        -activebackground #d9d9d9 -background white -borderwidth 1 \
        -buttonbackground SystemButtonFace -buttondownrelief raised \
        -buttonuprelief raised -cursor xterm \
        -disabledbackground SystemButtonFace -disabledforeground #a3a3a3 \
        -exportselection 0 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -from 0.0 -highlightbackground black \
        -highlightcolor #000000 -highlightthickness 0 -increment 1.0 \
        -insertbackground #000000 -insertborderwidth 0 -insertofftime 300 \
        -insertontime 600 -insertwidth 2 -justify left -relief sunken \
        -readonlybackground SystemButtonFace -repeatdelay 400 \
        -repeatinterval 100 -selectbackground #d9d9d9 -selectborderwidth 0 \
        -selectforeground black -state normal -to 100.0 -validate none \
        -width 53 -wrap 0 
    vTcl:DefineAlias "$site_4_0.spi60" "SpinboxC" vTcl:WidgetProc "Toplevel0" 1
    spinbox "$site_4_0.spi59" \
        -activebackground #d9d9d9 -background white -borderwidth 1 \
        -buttonbackground SystemButtonFace -buttondownrelief raised \
        -buttonuprelief raised -cursor xterm \
        -disabledbackground SystemButtonFace -disabledforeground #a3a3a3 \
        -exportselection 0 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -from 0.0 -highlightbackground black \
        -highlightcolor #000000 -highlightthickness 0 -increment 1.0 \
        -insertbackground #000000 -insertborderwidth 0 -insertofftime 300 \
        -insertontime 600 -insertwidth 2 -justify left -relief sunken \
        -readonlybackground SystemButtonFace -repeatdelay 400 \
        -repeatinterval 100 -selectbackground #d9d9d9 -selectborderwidth 0 \
        -selectforeground black -state normal -to 100.0 -validate none \
        -width 53 -wrap 0 
    vTcl:DefineAlias "$site_4_0.spi59" "SpinboxB" vTcl:WidgetProc "Toplevel0" 1
    spinbox "$site_4_0.spi61" \
        -activebackground #d9d9d9 -background white -borderwidth 1 \
        -buttonbackground SystemButtonFace -buttondownrelief raised \
        -buttonuprelief raised -cursor xterm \
        -disabledbackground SystemButtonFace -disabledforeground #a3a3a3 \
        -exportselection 0 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -from 0.0 -highlightbackground black \
        -highlightcolor #000000 -highlightthickness 0 -increment 1.0 \
        -insertbackground #000000 -insertborderwidth 0 -insertofftime 300 \
        -insertontime 600 -insertwidth 2 -justify left -relief sunken \
        -readonlybackground SystemButtonFace -repeatdelay 400 \
        -repeatinterval 100 -selectbackground #d9d9d9 -selectborderwidth 0 \
        -selectforeground black -state normal -to 100.0 -validate none \
        -width 53 -wrap 0 
    vTcl:DefineAlias "$site_4_0.spi61" "SpinboxA" vTcl:WidgetProc "Toplevel0" 1
    spinbox "$site_4_0.spi71" \
        -activebackground #d9d9d9 -background white -borderwidth 1 \
        -buttonbackground SystemButtonFace -buttondownrelief raised \
        -buttonuprelief raised -cursor xterm \
        -disabledbackground SystemButtonFace -disabledforeground #a3a3a3 \
        -exportselection 0 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -from 0.0 -highlightbackground black \
        -highlightcolor #000000 -highlightthickness 0 -increment 1.0 \
        -insertbackground #000000 -insertborderwidth 0 -insertofftime 300 \
        -insertontime 600 -insertwidth 2 -justify left -relief sunken \
        -readonlybackground SystemButtonFace -repeatdelay 400 \
        -repeatinterval 100 -selectbackground #d9d9d9 -selectborderwidth 0 \
        -selectforeground black -state normal -to 100.0 -validate none \
        -width 52 -wrap 0 
    vTcl:DefineAlias "$site_4_0.spi71" "Spinbox5" vTcl:WidgetProc "Toplevel0" 1
    label "$site_4_0.lab69" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 -text "Labelint5" \
        -underline -1 -width 83 -wraplength 0 
    vTcl:DefineAlias "$site_4_0.lab69" "ItemLabelint5" vTcl:WidgetProc "Toplevel0" 1
    label "$site_4_0.lab50" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 -text "Labelint5" \
        -underline -1 -width 83 -wraplength 0 
    vTcl:DefineAlias "$site_4_0.lab50" "ItemLabelint6" vTcl:WidgetProc "Toplevel0" 1
    spinbox "$site_4_0.spi49" \
        -activebackground #d9d9d9 -background white -borderwidth 1 \
        -buttonbackground SystemButtonFace -buttondownrelief raised \
        -buttonuprelief raised -cursor xterm \
        -disabledbackground SystemButtonFace -disabledforeground #a3a3a3 \
        -exportselection 0 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -from 0.0 -highlightbackground black \
        -highlightcolor #000000 -highlightthickness 0 -increment 1.0 \
        -insertbackground #000000 -insertborderwidth 0 -insertofftime 300 \
        -insertontime 600 -insertwidth 2 -justify left -relief sunken \
        -readonlybackground SystemButtonFace -repeatdelay 400 \
        -repeatinterval 100 -selectbackground #d9d9d9 -selectborderwidth 0 \
        -selectforeground black -state normal -to 100.0 -validate none \
        -width 52 -wrap 0 
    vTcl:DefineAlias "$site_4_0.spi49" "Spinbox6" vTcl:WidgetProc "Toplevel0" 1
    checkbutton "$site_4_0.che52" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 25 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 1 -indicatoron 1 \
        -justify left -offrelief raised -offvalue 0 -onvalue 1 -padx 1 \
        -pady 1 -relief flat -selectcolor SystemWindow -state normal \
        -text "check1" -underline -1 -variable "check1" -width 112 \
        -wraplength 0 
    vTcl:DefineAlias "$site_4_0.che52" "Checkbutton1" vTcl:WidgetProc "Toplevel0" 1
    checkbutton "$site_4_0.che50" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 25 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 1 -indicatoron 1 \
        -justify left -offrelief raised -offvalue 0 -onvalue 1 -padx 1 \
        -pady 1 -relief flat -selectcolor SystemWindow -state normal \
        -text "check2" -underline -1 -variable "check2" -width 112 \
        -wraplength 0 
    vTcl:DefineAlias "$site_4_0.che50" "Checkbutton2" vTcl:WidgetProc "Toplevel0" 1
    checkbutton "$site_4_0.che51" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 25 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 1 -indicatoron 1 \
        -justify left -offrelief raised -offvalue 0 -onvalue 1 -padx 1 \
        -pady 1 -relief flat -selectcolor SystemWindow -state normal \
        -text "check3" -underline -1 -variable "check3" -width 112 \
        -wraplength 0 
    vTcl:DefineAlias "$site_4_0.che51" "Checkbutton3" vTcl:WidgetProc "Toplevel0" 1
    vTcl::widgets::ttk::scrolledtext::CreateCmd "$site_4_0.scr86" \
        -borderwidth 2 -relief groove -background #d9d9d9 -container 0 \
        -height 75 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -padx 0 -pady 0 -takefocus 0 -width 125 
    vTcl:DefineAlias "$site_4_0.scr86" "ScrolledtextItem" vTcl:WidgetProc "Toplevel0" 1

    $site_4_0.scr86.01 configure -background white \
        -exportselection 0 \
        -font "-family {DejaVu Sans} -size 12" \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #000000 \
        -insertbackground #000000 \
        -insertborderwidth 3 \
        -selectbackground #d9d9d9 \
        -selectforeground black \
        -width 10 \
        -wrap none
    label "$site_4_0.lab49" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 -text "Nieuw item:" \
        -underline -1 -width 94 -wraplength 0 
    vTcl:DefineAlias "$site_4_0.lab49" "ItemLabelNieuw" vTcl:WidgetProc "Toplevel0" 1
    spinbox "$site_4_0.spi66" \
        -activebackground #d9d9d9 -background white -borderwidth 1 \
        -buttonbackground SystemButtonFace -buttondownrelief raised \
        -buttonuprelief raised -cursor xterm \
        -disabledbackground SystemButtonFace -disabledforeground #a3a3a3 \
        -exportselection 0 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -from 0.0 -highlightbackground black \
        -highlightcolor #000000 -highlightthickness 0 -increment 1.0 \
        -insertbackground #000000 -insertborderwidth 0 -insertofftime 300 \
        -insertontime 600 -insertwidth 2 -justify left -relief sunken \
        -readonlybackground SystemButtonFace -repeatdelay 400 \
        -repeatinterval 100 -selectbackground #d9d9d9 -selectborderwidth 0 \
        -selectforeground black -state normal -to 100.0 -validate none \
        -width 52 -wrap 0 
    vTcl:DefineAlias "$site_4_0.spi66" "Spinbox1" vTcl:WidgetProc "Toplevel0" 1
    label "$site_4_0.lab54" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 \
        -text "displayport_out:" -underline -1 -width 132 -wraplength 0 
    vTcl:DefineAlias "$site_4_0.lab54" "ItemLabelout" vTcl:WidgetProc "Toplevel0" 1
    spinbox "$site_4_0.spi53" \
        -activebackground #d9d9d9 -background white -borderwidth 1 \
        -buttonbackground SystemButtonFace -buttondownrelief raised \
        -buttonuprelief raised -cursor xterm \
        -disabledbackground SystemButtonFace -disabledforeground #a3a3a3 \
        -exportselection 0 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -from 0.0 -highlightbackground black \
        -highlightcolor #000000 -highlightthickness 0 -increment 1.0 \
        -insertbackground #000000 -insertborderwidth 0 -insertofftime 300 \
        -insertontime 600 -insertwidth 2 -justify left -relief sunken \
        -readonlybackground SystemButtonFace -repeatdelay 400 \
        -repeatinterval 100 -selectbackground #d9d9d9 -selectborderwidth 0 \
        -selectforeground black -state normal -to 100.0 -validate none \
        -width 53 -wrap 0 
    vTcl:DefineAlias "$site_4_0.spi53" "SpinboxOut" vTcl:WidgetProc "Toplevel0" 1
    spinbox "$site_4_0.spi62" \
        -activebackground #d9d9d9 -background white -borderwidth 1 \
        -buttonbackground SystemButtonFace -buttondownrelief raised \
        -buttonuprelief raised -cursor xterm \
        -disabledbackground SystemButtonFace -disabledforeground #a3a3a3 \
        -exportselection 0 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -from 0.0 -highlightbackground black \
        -highlightcolor #000000 -highlightthickness 0 -increment 1.0 \
        -insertbackground #000000 -insertborderwidth 0 -insertofftime 300 \
        -insertontime 600 -insertwidth 2 -justify left -relief sunken \
        -readonlybackground SystemButtonFace -repeatdelay 400 \
        -repeatinterval 100 -selectbackground #d9d9d9 -selectborderwidth 0 \
        -selectforeground black -state normal -to 100.0 -validate none \
        -width 52 -wrap 0 
    vTcl:DefineAlias "$site_4_0.spi62" "SpinboxIn" vTcl:WidgetProc "Toplevel0" 1
    label "$site_4_0.lab55" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 \
        -text "displayport_in:" -underline -1 -width 124 -wraplength 0 
    vTcl:DefineAlias "$site_4_0.lab55" "ItemLabelin" vTcl:WidgetProc "Toplevel0" 1
    label "$site_4_0.lab57" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 -text "A_kwaliteit:" \
        -underline -1 -width 92 -wraplength 0 
    vTcl:DefineAlias "$site_4_0.lab57" "ItemLabelA" vTcl:WidgetProc "Toplevel0" 1
    label "$site_4_0.lab58" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 -text "B_kwaliteit:" \
        -underline -1 -width 92 -wraplength 0 
    vTcl:DefineAlias "$site_4_0.lab58" "ItemLabelB" vTcl:WidgetProc "Toplevel0" 1
    label "$site_4_0.lab56" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 -text "C_kwaliteit:" \
        -underline -1 -width 92 -wraplength 0 
    vTcl:DefineAlias "$site_4_0.lab56" "ItemLabelC" vTcl:WidgetProc "Toplevel0" 1
    label "$site_4_0.lab89" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 \
        -text "Item wijzigen:" -underline -1 -width 114 -wraplength 0 
    vTcl:DefineAlias "$site_4_0.lab89" "ItemLabelAanpassen" vTcl:WidgetProc "Toplevel0" 1
    button "$site_4_0.but88" \
        -activebackground #d9d9d9 -activeforeground black -anchor center \
        -background #bbffbb -borderwidth 2 -command "on_btnAanpassen" \
        -compound left -default disabled -disabledforeground #a3a3a3 \
        -font "-family {DejaVu Sans} -size 12" -foreground #000000 -height 26 \
        -highlightbackground #bbffbb -highlightcolor #000000 \
        -highlightthickness 1 -justify center -padx 1 -pady 1 -relief raised \
        -repeatdelay 0 -repeatinterval 0 -state normal -text "Aanpassen" \
        -underline -1 -width 107 -wraplength 0 
    vTcl:DefineAlias "$site_4_0.but88" "btnAanpassen" vTcl:WidgetProc "Toplevel0" 1
    button "$site_4_0.but50" \
        -activebackground #d9d9d9 -activeforeground black -anchor center \
        -background #aed7ff -borderwidth 2 -command "on_btnToevoegen" \
        -compound left -default disabled -disabledforeground #a3a3a3 \
        -font "-family {DejaVu Sans} -size 12" -foreground #000000 -height 26 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 1 -justify center -padx 1 -pady 1 -relief raised \
        -repeatdelay 0 -repeatinterval 0 -state normal -text "Toevoegen" \
        -underline -1 -width 107 -wraplength 0 
    vTcl:DefineAlias "$site_4_0.but50" "btnToevoegen" vTcl:WidgetProc "Toplevel0" 1
# add p1 basename = $site_4_0.lab87
    place $site_4_0.lab87 \
        -in $site_4_0 -x 0 -relx 0.632 -y 0 -rely 0.759 -width 0 \
        -relwidth 0.074 -height 0 -relheight 0.145 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.spi72
    place $site_4_0.spi72 \
        -in $site_4_0 -x 0 -relx 0.375 -y 0 -rely 0.138 -width 0 \
        -relwidth 0.038 -height 0 -relheight 0.131 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.ent77
    place $site_4_0.ent77 \
        -in $site_4_0 -x 0 -relx 0.471 -y 0 -rely 0.138 -width 104 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_4_0.ent79
    place $site_4_0.ent79 \
        -in $site_4_0 -x 0 -relx 0.471 -y 0 -rely 0.345 -width 104 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_4_0.ent85
    place $site_4_0.ent85 \
        -in $site_4_0 -x 0 -relx 0.471 -y 0 -rely 0.552 -width 104 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_4_0.ent81
    place $site_4_0.ent81 \
        -in $site_4_0 -x 0 -relx 0.61 -y 0 -rely 0.138 -width 104 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_4_0.ent84
    place $site_4_0.ent84 \
        -in $site_4_0 -x 0 -relx 0.61 -y 0 -rely 0.345 -width 104 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_4_0.ent80
    place $site_4_0.ent80 \
        -in $site_4_0 -x 0 -relx 0.61 -y 0 -rely 0.552 -width 104 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_4_0.lab63
    place $site_4_0.lab63 \
        -in $site_4_0 -x 0 -relx 0.213 -y 0 -rely 0.138 -width 0 \
        -relwidth 0.059 -height 0 -relheight 0.145 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.lab65
    place $site_4_0.lab65 \
        -in $site_4_0 -x 0 -relx 0.213 -y 0 -rely 0.345 -width 0 \
        -relwidth 0.059 -height 0 -relheight 0.145 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.lab64
    place $site_4_0.lab64 \
        -in $site_4_0 -x 0 -relx 0.213 -y 0 -rely 0.552 -width 0 \
        -relwidth 0.059 -height 0 -relheight 0.145 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.lab70
    place $site_4_0.lab70 \
        -in $site_4_0 -x 0 -relx 0.316 -y 0 -rely 0.138 -width 0 \
        -relwidth 0.059 -height 0 -relheight 0.145 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.lab73
    place $site_4_0.lab73 \
        -in $site_4_0 -x 0 -relx 0.419 -y 0 -rely 0.138 -width 0 \
        -relwidth 0.051 -height 0 -relheight 0.145 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.lab74
    place $site_4_0.lab74 \
        -in $site_4_0 -x 0 -relx 0.419 -y 0 -rely 0.345 -width 0 \
        -relwidth 0.05 -height 0 -relheight 0.145 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.lab83
    place $site_4_0.lab83 \
        -in $site_4_0 -x 0 -relx 0.419 -y 0 -rely 0.552 -width 0 \
        -relwidth 0.05 -height 0 -relheight 0.145 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.lab76
    place $site_4_0.lab76 \
        -in $site_4_0 -x 0 -relx 0.559 -y 0 -rely 0.138 -width 0 \
        -relwidth 0.05 -height 0 -relheight 0.145 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.lab82
    place $site_4_0.lab82 \
        -in $site_4_0 -x 0 -relx 0.559 -y 0 -rely 0.345 -width 0 \
        -relwidth 0.05 -height 0 -relheight 0.145 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.lab75
    place $site_4_0.lab75 \
        -in $site_4_0 -x 0 -relx 0.559 -y 0 -rely 0.552 -width 0 \
        -relwidth 0.05 -height 0 -relheight 0.145 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.spi68
    place $site_4_0.spi68 \
        -in $site_4_0 -x 0 -relx 0.272 -y 0 -rely 0.345 -width 0 \
        -relwidth 0.038 -height 0 -relheight 0.131 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.spi67
    place $site_4_0.spi67 \
        -in $site_4_0 -x 0 -relx 0.272 -y 0 -rely 0.552 -width 0 \
        -relwidth 0.038 -height 0 -relheight 0.131 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.spi60
    place $site_4_0.spi60 \
        -in $site_4_0 -x 0 -relx 0.171 -y 0 -rely 0.552 -width 0 \
        -relwidth 0.039 -height 0 -relheight 0.131 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.spi59
    place $site_4_0.spi59 \
        -in $site_4_0 -x 0 -relx 0.171 -y 0 -rely 0.345 -width 0 \
        -relwidth 0.039 -height 0 -relheight 0.131 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.spi61
    place $site_4_0.spi61 \
        -in $site_4_0 -x 0 -relx 0.171 -y 0 -rely 0.138 -width 0 \
        -relwidth 0.039 -height 0 -relheight 0.131 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.spi71
    place $site_4_0.spi71 \
        -in $site_4_0 -x 0 -relx 0.375 -y 0 -rely 0.345 -width 0 \
        -relwidth 0.038 -height 0 -relheight 0.131 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.lab69
    place $site_4_0.lab69 \
        -in $site_4_0 -x 0 -relx 0.316 -y 0 -rely 0.345 -width 0 \
        -relwidth 0.059 -height 0 -relheight 0.145 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.lab50
    place $site_4_0.lab50 \
        -in $site_4_0 -x 0 -relx 0.316 -y 0 -rely 0.552 -width 0 \
        -relwidth 0.059 -height 0 -relheight 0.145 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.spi49
    place $site_4_0.spi49 \
        -in $site_4_0 -x 0 -relx 0.375 -y 0 -rely 0.552 -width 0 \
        -relwidth 0.038 -height 0 -relheight 0.131 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.che52
    place $site_4_0.che52 \
        -in $site_4_0 -x 0 -relx 0.007 -y 0 -rely 0.138 -width 0 \
        -relwidth 0.082 -height 0 -relheight 0.172 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.che50
    place $site_4_0.che50 \
        -in $site_4_0 -x 0 -relx 0.007 -y 0 -rely 0.345 -width 0 \
        -relwidth 0.082 -height 0 -relheight 0.172 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.che51
    place $site_4_0.che51 \
        -in $site_4_0 -x 0 -relx 0.007 -y 0 -rely 0.552 -width 0 \
        -relwidth 0.082 -height 0 -relheight 0.172 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.scr86
    place $site_4_0.scr86 \
        -in $site_4_0 -x 0 -relx 0.704 -y 0 -rely 0.069 -width 0 \
        -relwidth 0.293 -height 0 -relheight 0.917 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.lab49
    place $site_4_0.lab49 \
        -in $site_4_0 -x 0 -relx 0.478 -y 0 -rely 0.759 -width 0 \
        -relwidth 0.069 -height 0 -relheight 0.145 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.spi66
    place $site_4_0.spi66 \
        -in $site_4_0 -x 0 -relx 0.272 -y 0 -rely 0.138 -width 0 \
        -relwidth 0.038 -height 0 -relheight 0.131 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.lab54
    place $site_4_0.lab54 \
        -in $site_4_0 -x 0 -relx 0.14 -y 0 -rely 0.759 -width 0 \
        -relwidth 0.096 -height 0 -relheight 0.145 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.spi53
    place $site_4_0.spi53 \
        -in $site_4_0 -x 0 -relx 0.243 -y 0 -rely 0.759 -width 0 \
        -relwidth 0.04 -height 0 -relheight 0.131 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.spi62
    place $site_4_0.spi62 \
        -in $site_4_0 -x 0 -relx 0.096 -y 0 -rely 0.759 -width 0 \
        -relwidth 0.038 -height 0 -relheight 0.131 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.lab55
    place $site_4_0.lab55 \
        -in $site_4_0 -x 0 -relx 0.007 -y 0 -rely 0.759 -width 0 \
        -relwidth 0.088 -height 0 -relheight 0.145 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.lab57
    place $site_4_0.lab57 \
        -in $site_4_0 -x 0 -relx 0.103 -y 0 -rely 0.138 -width 0 \
        -relwidth 0.068 -height 0 -relheight 0.145 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.lab58
    place $site_4_0.lab58 \
        -in $site_4_0 -x 0 -relx 0.103 -y 0 -rely 0.345 -width 0 \
        -relwidth 0.068 -height 0 -relheight 0.145 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.lab56
    place $site_4_0.lab56 \
        -in $site_4_0 -x 0 -relx 0.103 -y 0 -rely 0.552 -width 0 \
        -relwidth 0.068 -height 0 -relheight 0.145 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.lab89
    place $site_4_0.lab89 \
        -in $site_4_0 -x 0 -relx 0.309 -y 0 -rely 0.759 -width 0 \
        -relwidth 0.084 -height 0 -relheight 0.145 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_4_0.but88
    place $site_4_0.but88 \
        -in $site_4_0 -x 0 -relx 0.397 -y 0 -rely 0.759 -width 107 \
        -relwidth 0 -height 26 -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_4_0.but50
    place $site_4_0.but50 \
        -in $site_4_0 -x 0 -relx 0.551 -y 0 -rely 0.759 -width 107 \
        -relwidth 0 -height 26 -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $site_3_0.lab49
# add p1 basename = $site_3_0.lab59
    place $site_3_0.lab59 \
        -in $site_3_0 -x 0 -relx 0.005 -y 0 -rely 0.438 -width 0 \
        -relwidth 0.257 -height 0 -relheight 0.529 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_3_0.lab50
    place $site_3_0.lab50 \
        -in $site_3_0 -x 0 -relx 0.388 -y 0 -rely 0.073 -width 0 \
        -relwidth 0.484 -height 0 -relheight 0.347 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_3_0.but54
    place $site_3_0.but54 \
        -in $site_3_0 -x 0 -relx 0.931 -y 0 -rely 0.182 -width 100 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_3_0.but59
    place $site_3_0.but59 \
        -in $site_3_0 -x 0 -relx 0.323 -y 0 -rely 0.255 -width 100 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_3_0.lab51
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.016 -y 0 -rely 0.146 -width 0 \
        -relwidth 0.082 -height 0 -relheight 0.084 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_3_0.lab58
    place $site_3_0.lab58 \
        -in $site_3_0 -x 0 -relx 0.113 -y 0 -rely 0.146 -width 0 \
        -relwidth 0.074 -height 0 -relheight 0.106 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_3_0.lab52
    place $site_3_0.lab52 \
        -in $site_3_0 -x 0 -relx 0.215 -y 0 -rely 0.146 -width 0 \
        -relwidth 0.074 -height 0 -relheight 0.106 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_3_0.ent49
    place $site_3_0.ent49 \
        -in $site_3_0 -x 0 -relx 0.215 -y 0 -rely 0.255 -width 170 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_3_0.ent57
    place $site_3_0.ent57 \
        -in $site_3_0 -x 0 -relx 0.113 -y 0 -rely 0.255 -width 160 \
        -relwidth 0 -height 30 -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $site_3_0.men61
    place $site_3_0.men61 \
        -in $site_3_0 -x 0 -relx 0.016 -y 0 -rely 0.255 -width 0 \
        -relwidth 0.077 -height 0 -relheight 0.12 -anchor nw \
        -bordermode ignore 
# add p1 basename = $site_3_0.lab49
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.264 -y 0 -rely 0.438 -width 0 \
        -relwidth 0.732 -height 0 -relheight 0.529 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
# add p1 basename = $top.lab55
    place $top.lab55 \
        -in $top -x 0 -relx 0.01 -y 0 -rely 0.295 -width 0 -relwidth 0.98 \
        -height 0 -relheight 0.686 -anchor nw -bordermode ignore 
# add p1 basename = $top.lab54
    place $top.lab54 \
        -in $top -x 0 -relx 0.01 -y 0 -rely 0.01 -width 0 -relwidth 0.98 \
        -height 0 -relheight 0.281 -anchor nw -bordermode ignore 

############# Spot ttt ##############################

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top2 {base} {
    global vTcl
    if {$base == ""} {
        set base .top2
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base

############ toplevel.wgt #############################
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -borderwidth 0 -relief flat -background #d9d9d9 -container 0 \
        -height 0 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -padx 0 -pady 0 -takefocus 0 -width 0 
    wm focusmodel $top passive
    wm geometry $top 600x366+610+260
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Login Scherm"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel2" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    button "$top.but55" \
        -activebackground #d9d9d9 -activeforeground black -anchor center \
        -background #d9d9d9 -borderwidth 2 -command "on_btnLogin" \
        -compound left -default disabled -disabledforeground #a3a3a3 \
        -font "-family {DejaVu Sans} -size 14" -foreground #000000 -height 46 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 1 -justify center -padx 1 -pady 1 -relief raised \
        -repeatdelay 0 -repeatinterval 0 -state normal -text "Login" \
        -underline -1 -width 157 -wraplength 0 
    vTcl:DefineAlias "$top.but55" "Button_login" vTcl:WidgetProc "Toplevel2" 1
    entry "$top.ent49" \
        -background #ffffff -borderwidth 1 -cursor xterm \
        -disabledbackground SystemButtonFace -disabledforeground #a3a3a3 \
        -exportselection 0 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 \
        -insertbackground #000000 -insertborderwidth 0 -insertofftime 300 \
        -insertontime 600 -insertwidth 2 -justify left \
        -readonlybackground SystemButtonFace -relief sunken \
        -selectbackground #d9d9d9 -selectborderwidth 0 \
        -selectforeground black -state normal -validate none -width 184 
    vTcl:DefineAlias "$top.ent49" "usernameEntry" vTcl:WidgetProc "Toplevel2" 1
    bind $top.ent49 <Key-Return> {
        lambda e: usernameEnter(e)
    }
    label "$top.lab52" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 -text "Wachtwoord:" \
        -underline -1 -width 114 -wraplength 0 
    vTcl:DefineAlias "$top.lab52" "wachtwoordLabel" vTcl:WidgetProc "Toplevel2" 1
    entry "$top.ent51" \
        -background #ffffff -borderwidth 1 -cursor xterm \
        -disabledbackground SystemButtonFace -disabledforeground #a3a3a3 \
        -exportselection 0 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 \
        -insertbackground #000000 -insertborderwidth 0 -insertofftime 300 \
        -insertontime 600 -insertwidth 2 -justify left \
        -readonlybackground SystemButtonFace -relief sunken \
        -selectbackground #d9d9d9 -selectborderwidth 0 \
        -selectforeground black -state normal -validate none -width 184 
    vTcl:DefineAlias "$top.ent51" "wachtwoordEntry" vTcl:WidgetProc "Toplevel2" 1
    bind $top.ent51 <Key-Return> {
        lambda e: wachtwoordEnter(e)
    }
    label "$top.lab51" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 \
        -text "Gebruikersnaam:" -underline -1 -width 144 -wraplength 0 
    vTcl:DefineAlias "$top.lab51" "gebruikersnaamLabel" vTcl:WidgetProc "Toplevel2" 1
    label "$top.lab53" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 \
        -text "Mede mogelijk gemaakt door Roads Technology" -underline -1 \
        -width 374 -wraplength 0 
    vTcl:DefineAlias "$top.lab53" "creditLabel_1" vTcl:WidgetProc "Toplevel2" 1
    label "$top.lab50" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 \
        -text "Gemaakt door Jelle ten Broeke" -underline -1 -width 244 \
        -wraplength 0 
    vTcl:DefineAlias "$top.lab50" "creditLabel" vTcl:WidgetProc "Toplevel2" 1
    label "$top.lab54" \
        -activebackground #d9d9d9 -activeforeground #000000 -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 \
        -font "-family {DejaVu Sans} -size 20 -weight bold" \
        -foreground #0000ff -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 -text "RoadsDepot" \
        -underline -1 -width 194 -wraplength 0 
    vTcl:DefineAlias "$top.lab54" "creditLabel_2" vTcl:WidgetProc "Toplevel2" 1
    ###################
    # SETTING GEOMETRY
    ###################
# add p1 basename = $top.but55
    place $top.but55 \
        -in $top -x 0 -relx 0.367 -y 0 -rely 0.489 -width 157 -relwidth 0 \
        -height 46 -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $top.ent49
    place $top.ent49 \
        -in $top -x 0 -relx 0.467 -y 0 -rely 0.219 -width 184 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $top.lab52
    place $top.lab52 \
        -in $top -x 0 -relx 0.267 -y 0 -rely 0.328 -width 0 -relwidth 0.19 \
        -height 0 -relheight 0.068 -anchor nw -bordermode ignore 
# add p1 basename = $top.ent51
    place $top.ent51 \
        -in $top -x 0 -relx 0.467 -y 0 -rely 0.328 -width 184 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $top.lab51
    place $top.lab51 \
        -in $top -x 0 -relx 0.222 -y 0 -rely 0.219 -width 0 -relwidth 0.24 \
        -height 0 -relheight 0.068 -anchor nw -bordermode ignore 
# add p1 basename = $top.lab53
    place $top.lab53 \
        -in $top -x 0 -relx 0.2 -y 0 -rely 0.765 -width 0 -relwidth 0.623 \
        -height 0 -relheight 0.068 -anchor nw -bordermode ignore 
# add p1 basename = $top.lab50
    place $top.lab50 \
        -in $top -x 0 -relx 0.3 -y 0 -rely 0.683 -width 0 -relwidth 0.407 \
        -height 0 -relheight 0.068 -anchor nw -bordermode ignore 
# add p1 basename = $top.lab54
    place $top.lab54 \
        -in $top -x 0 -relx 0.333 -y 0 -rely 0.082 -width 0 -relwidth 0.323 \
        -height 0 -relheight 0.068 -anchor nw -bordermode ignore 

############# Spot ttt ##############################

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top3 {base} {
    global vTcl
    if {$base == ""} {
        set base .top3
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base

############ toplevel.wgt #############################
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -borderwidth 0 -relief flat -background #d9d9d9 -container 0 \
        -height 0 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -padx 0 -pady 0 -takefocus 0 -width 0 
    wm focusmodel $top passive
    wm geometry $top 600x450+560+310
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Logboek Database"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel3" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    label "$top.lab59" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 -text "Wachtwoord:" \
        -underline -1 -width 114 -wraplength 0 
    vTcl:DefineAlias "$top.lab59" "dbwwLabel" vTcl:WidgetProc "Toplevel3" 1
    entry "$top.ent60" \
        -background #ffffff -borderwidth 1 -cursor xterm \
        -disabledbackground SystemButtonFace -disabledforeground #a3a3a3 \
        -exportselection 0 -font "TkFixedFont" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -insertbackground #000000 -insertborderwidth 0 \
        -insertofftime 300 -insertontime 600 -insertwidth 2 -justify left \
        -readonlybackground SystemButtonFace -relief sunken \
        -selectbackground #d9d9d9 -selectborderwidth 0 \
        -selectforeground black -state normal -validate none -width 274 
    vTcl:DefineAlias "$top.ent60" "dbEntry" vTcl:WidgetProc "Toplevel3" 1
    label "$top.lab58" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 -text "Database:" \
        -underline -1 -width 84 -wraplength 0 
    vTcl:DefineAlias "$top.lab58" "dbLabel" vTcl:WidgetProc "Toplevel3" 1
    entry "$top.ent61" \
        -background #ffffff -borderwidth 1 -cursor xterm \
        -disabledbackground SystemButtonFace -disabledforeground #a3a3a3 \
        -exportselection 0 -font "TkFixedFont" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -insertbackground #000000 -insertborderwidth 0 \
        -insertofftime 300 -insertontime 600 -insertwidth 2 -justify left \
        -readonlybackground SystemButtonFace -relief sunken \
        -selectbackground #d9d9d9 -selectborderwidth 0 \
        -selectforeground black -state normal -validate none -width 274 
    vTcl:DefineAlias "$top.ent61" "dbwwEntry" vTcl:WidgetProc "Toplevel3" 1
    button "$top.but62" \
        -activebackground #d9d9d9 -activeforeground black -anchor center \
        -background #d9d9d9 -borderwidth 2 -command "on_andersBtn" \
        -compound left -default disabled -disabledforeground #a3a3a3 \
        -font "-family {DejaVu Sans} -size 12" -foreground #000000 -height 30 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 1 -justify center -padx 1 -pady 1 -relief raised \
        -repeatdelay 0 -repeatinterval 0 -state normal -text "Kies anders" \
        -underline -1 -width 117 -wraplength 0 
    vTcl:DefineAlias "$top.but62" "andersBtn" vTcl:WidgetProc "Toplevel3" 1
    button "$top.but64" \
        -activebackground #d9d9d9 -activeforeground black -anchor center \
        -background #d9d9d9 -borderwidth 2 -command "on_okBtn" -compound left \
        -default disabled -disabledforeground #a3a3a3 \
        -font "-family {DejaVu Sans} -size 12" -foreground #000000 -height 30 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 1 -justify center -padx 1 -pady 1 -relief raised \
        -repeatdelay 0 -repeatinterval 0 -state normal -text "OK" \
        -underline -1 -width 117 -wraplength 0 
    vTcl:DefineAlias "$top.but64" "okBtn" vTcl:WidgetProc "Toplevel3" 1
    ###################
    # SETTING GEOMETRY
    ###################
# add p1 basename = $top.lab59
    place $top.lab59 \
        -in $top -x 0 -relx 0.158 -y 0 -rely 0.356 -width 0 -relwidth 0.19 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
# add p1 basename = $top.ent60
    place $top.ent60 \
        -in $top -x 0 -relx 0.35 -y 0 -rely 0.222 -width 274 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $top.lab58
    place $top.lab58 \
        -in $top -x 0 -relx 0.2 -y 0 -rely 0.222 -width 0 -relwidth 0.14 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
# add p1 basename = $top.ent61
    place $top.ent61 \
        -in $top -x 0 -relx 0.35 -y 0 -rely 0.356 -width 274 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $top.but62
    place $top.but62 \
        -in $top -x 0 -relx 0.15 -y 0 -rely 0.622 -width 117 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $top.but64
    place $top.but64 \
        -in $top -x 0 -relx 0.6 -y 0 -rely 0.622 -width 117 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 

############# Spot ttt ##############################

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top4 {base} {
    global vTcl
    if {$base == ""} {
        set base .top4
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base

############ toplevel.wgt #############################
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -borderwidth 0 -relief flat -background #d9d9d9 -container 0 \
        -height 0 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -padx 0 -pady 0 -takefocus 0 -width 0 
    wm focusmodel $top passive
    wm geometry $top 600x450+510+360
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Nieuw Log Database"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel4" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    label "$top.lab51" \
        -activebackground #d9d9d9 -activeforeground black -anchor center \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 \
        -text "RoadsDepotLog2026" -underline -1 -width 264 -wraplength 0 
    vTcl:DefineAlias "$top.lab51" "nieuwenaamLabel" vTcl:WidgetProc "Toplevel4" 1
    label "$top.lab49" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 \
        -text "Naam van nieuwe Log database:" -underline -1 -width 264 \
        -wraplength 0 
    vTcl:DefineAlias "$top.lab49" "nieuwlogLabel" vTcl:WidgetProc "Toplevel4" 1
    entry "$top.ent54" \
        -background #ffffff -borderwidth 1 -cursor xterm \
        -disabledbackground SystemButtonFace -disabledforeground #a3a3a3 \
        -exportselection 0 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 \
        -insertbackground #000000 -insertborderwidth 0 -insertofftime 300 \
        -insertontime 600 -insertwidth 2 -justify left \
        -readonlybackground SystemButtonFace -relief sunken \
        -selectbackground #d9d9d9 -selectborderwidth 0 \
        -selectforeground black -state normal -validate none -width 294 
    vTcl:DefineAlias "$top.ent54" "nieuwwwEntry" vTcl:WidgetProc "Toplevel4" 1
    label "$top.lab52" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 -font "-family {DejaVu Sans} -size 12" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 \
        -text "Kies een NIEUW wachtwoord voor de database:" -underline -1 \
        -width 384 -wraplength 0 
    vTcl:DefineAlias "$top.lab52" "nieuwlogwwLabel" vTcl:WidgetProc "Toplevel4" 1
    label "$top.lab56" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -borderwidth 2 -compound left \
        -disabledforeground #a3a3a3 \
        -font "-family {DejaVu Sans} -size 12 -weight bold" \
        -foreground #000000 -height 0 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 \
        -text "Dit wachtwoord moet je ZELF ergens opslaan!" -underline -1 \
        -width 424 -wraplength 0 
    vTcl:DefineAlias "$top.lab56" "waarschuwingLabel" vTcl:WidgetProc "Toplevel4" 1
    button "$top.but58" \
        -activebackground #d9d9d9 -activeforeground black -anchor center \
        -background #d9d9d9 -borderwidth 2 -command "on_logokbtn" \
        -compound left -default disabled -disabledforeground #a3a3a3 \
        -font "-family {DejaVu Sans} -size 12" -foreground #000000 -height 30 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 1 -justify center -padx 1 -pady 1 -relief raised \
        -repeatdelay 0 -repeatinterval 0 -state normal -text "OK" \
        -underline -1 -width 100 -wraplength 0 
    vTcl:DefineAlias "$top.but58" "logokBtn" vTcl:WidgetProc "Toplevel4" 1
    button "$top.but57" \
        -activebackground #d9d9d9 -activeforeground black -anchor center \
        -background #d9d9d9 -borderwidth 2 -command "on_logafsluitbtn" \
        -compound left -default disabled -disabledforeground #a3a3a3 \
        -font "-family {DejaVu Sans} -size 12" -foreground #000000 -height 30 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 1 -justify center -padx 1 -pady 1 -relief raised \
        -repeatdelay 0 -repeatinterval 0 -state normal -text "Afsluiten" \
        -underline -1 -width 100 -wraplength 0 
    vTcl:DefineAlias "$top.but57" "logafsluitBtn" vTcl:WidgetProc "Toplevel4" 1
    ###################
    # SETTING GEOMETRY
    ###################
# add p1 basename = $top.lab51
    place $top.lab51 \
        -in $top -x 0 -relx 0.283 -y 0 -rely 0.267 -width 0 -relwidth 0.44 \
        -height 0 -relheight 0.069 -anchor nw -bordermode ignore 
# add p1 basename = $top.lab49
    place $top.lab49 \
        -in $top -x 0 -relx 0.283 -y 0 -rely 0.2 -width 0 -relwidth 0.44 \
        -height 0 -relheight 0.069 -anchor nw -bordermode ignore 
# add p1 basename = $top.ent54
    place $top.ent54 \
        -in $top -x 0 -relx 0.267 -y 0 -rely 0.444 -width 300 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $top.lab52
    place $top.lab52 \
        -in $top -x 0 -relx 0.2 -y 0 -rely 0.356 -width 0 -relwidth 0.64 \
        -height 0 -relheight 0.069 -anchor nw -bordermode ignore 
# add p1 basename = $top.lab56
    place $top.lab56 \
        -in $top -x 0 -relx 0.167 -y 0 -rely 0.556 -width 0 -relwidth 0.707 \
        -height 0 -relheight 0.069 -anchor nw -bordermode ignore 
# add p1 basename = $top.but58
    place $top.but58 \
        -in $top -x 0 -relx 0.717 -y 0 -rely 0.822 -width 100 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $top.but57
    place $top.but57 \
        -in $top -x 0 -relx 0.1 -y 0 -rely 0.822 -width 100 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 

############# Spot ttt ##############################

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}
set btop2 ""
if {$vTcl(borrow)} {
    set btop2 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop2 $vTcl(tops)] != -1} {
        set btop2 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop2
Window show .top2 $btop2
if {$vTcl(borrow)} {
    $btop2 configure -background plum
}
set btop3 ""
if {$vTcl(borrow)} {
    set btop3 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop3 $vTcl(tops)] != -1} {
        set btop3 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop3
Window show .top3 $btop3
if {$vTcl(borrow)} {
    $btop3 configure -background plum
}
set btop4 ""
if {$vTcl(borrow)} {
    set btop4 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop4 $vTcl(tops)] != -1} {
        set btop4 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop4
Window show .top4 $btop4
if {$vTcl(borrow)} {
    $btop4 configure -background plum
}

